### ISSUE TITLE
IllegalStateException is thrown when the document is tried to be closed

### ISSUE THREAD

**Issue by dorukkangal** [johngray1965/PdfiumAndroidKt#10]
Is it possible if the PdfDocument.close() method just returns like the PdfPage.close() method instead of throwing an exception when the document has already closed?

https://github.com/johngray1965/PdfiumAndroidKt/blob/main/PdfiumAndroid/src/main/java/io/legere/pdfiumandroid/PdfDocument.kt#L230
https://github.com/johngray1965/PdfiumAndroidKt/blob/main/PdfiumAndroid/src/main/java/io/legere/pdfiumandroid/PdfPage.kt#L579

**Comment by johngray1965** [comment]
In 1.0.17 there's a config option to not throw an exception when an operation is done on page or document that's closed.   Some of the API didn't have any clean way to return an error.  They will still throw an exception.
However, now there is another interface (available are a seperate artifact), that's based on arrow-kt, it never throws an exception (internally it will, but they will be caught and converter to errors).  See the Readme for more information.
