### ISSUE TITLE
Pdf annotations are not being drawn

### ISSUE THREAD

**Issue by migueloliveira-agentifai** [johngray1965/PdfiumAndroidKt#13]
.pdf documents that contain annotations are drawn without them.
https://github.com/barteksc/PdfiumAndroid , in which the library is based, draws the annotations.

**Comment by johngray1965** [comment]
Can you provide me with an example PDF?

**Comment by migueloliveira-agentifai** [comment]
Sorry, I completely forgot to upload it. Here it goes:
[pdfsample.pdf](https://github.com/johngray1965/PdfiumAndroidKt/files/13544592/pdfsample.pdf)
It will be missing "22/12/2023" when rendered with the sample app.

The macOS Preview app renders it as:
![Screenshot 2023-12-04 at 10 06 44](https://github.com/johngray1965/PdfiumAndroidKt/assets/128380751/ea610c97-66e9-4bf0-98cd-28a390090bf6)

**Comment by odmfl** [comment]
The annotations, currently in pdfium are only drawn, perhaps this also allows them to be compiled

Maybe with this commit you could also compile the pdf with foarms.  Would be great

https://github.com/trylevel/PdfiumAndroid/commit/a1912d9ad2726bd8d21fe532242f5f95469d2fbe

**Comment by johngray1965** [comment]
From the pdfium code:
//          flags       -   0 for normal display, or combination of the Page
//                          Rendering flags defined above. With the FPDF_ANNOT
//                          flag, it renders all annotations that do not require
//                          user-interaction, which are all annotations except
//                          widget and popup annotations.

We or in FPDF_ANNOT if renderAnnot is true on renderPageBitmap, but it still doesn't render that page correctly.   Happen to know what kind of annotation it is?

**Comment by migueloliveira-agentifai** [comment]
@johngray1965 unfortunately I don't, as I don't have access to how the pdf is generated. But I would say it is an interactive form, which is a type of widget.

**Comment by marain87** [comment]
It is related to FPDF_FFLDraw not called for new version of Pdfium render annotation and signature. 

I made some modifications to the code in [PdfiumAndroid](https://github.com/marain87/PdfiumAndroid) 
code ref to sample of [pdfium](https://github.com/bblanchon/pdfium-binaries/blob/master/example/example.c)

**Comment by odmfl** [comment]
@marain87 would you be able to add other functions such as search and more from these two repositories?

https://github.com/Lesmm/AndroidPdfViewer/tree/develop ( in this branch search and selection works)

https://github.com/TEA-ebook/AndroidPdfViewer (search, selection and highlighting should work here)

**Comment by johngray1965** [comment]
@odmfl those projejcts are viewers.  This projects wraps the native pdfium api to provide the APIs to an Android app.    We project isn't a viewer.  You are talking about viewer functionality.

**Comment by johngray1965** [comment]
In the next release, the annotations should work for renderPageBitmap without a matrix, but with a matrix.  FPDF_FFLDraw doesn't have a version that takes a matrix.

**Comment by johngray1965** [comment]
![Screenshot_20241104_133311](https://github.com/user-attachments/assets/1edbde25-dced-4045-8114-48c0c17a83d7)
