### ISSUE TITLE
Filled form fields are rendered blank

### ISSUE THREAD

**Issue by roudikk** [johngray1965/PdfiumAndroidKt#5]
Trying to render a page to a bitmap doesn't render filled from fields.

Expected:

<img width="826" alt="image" src="https://github.com/johngray1965/PdfiumAndroidKt/assets/22520376/53cd4ff6-c82d-46da-8d90-c3e104c7d21a">

Actual:

<img width="324" alt="image" src="https://github.com/johngray1965/PdfiumAndroidKt/assets/22520376/497a079c-92d3-4ec5-b4a7-1c5d2af8b19e">

The code

```kotlin
val bitmap = Bitmap.createBitmap(
    size.width,
    size.height,
    Bitmap.Config.ARGB_8888,
)

page.renderPageBitmap(
    bitmap = bitmap,
    startX = 0,
    startY = 0,
    drawSizeX = size.width,
    drawSizeY = size.height,
    renderAnnot = true,
    textMask = true, // Tried with false as well
)
```

**Comment by johngray1965** [comment]
I see this problem with lots of other pdf things (outside of this library).  Often need flatten the pdf.  

For this project, all we do is make a nice wrapper for pdfium.   We don't maintain pdfium, just this wrapper that makes it available to Android (and using coroutines).

The problem you are seeing isn't in the wrapper.  And I'm not even sure if it's really a problem is pdfium or not.  I've seen the problem  with Adobe's Fill & Sign.
