### ISSUE TITLE
Using timber causes lint control to fail in projects that do not use timber

### ISSUE THREAD

**Issue by dorukkangal** [johngray1965/PdfiumAndroidKt#6]
Can you use android Log class instead of Timber?
Because it causes the lint control to fail in the classes we use `android.util.Log` and gives the following error:
![timber-lint-error](https://github.com/johngray1965/PdfiumAndroidKt/assets/1974587/835c5df0-05b2-43e9-a8b9-041df3cbb138)

**Comment by johngray1965** [comment]
I add a comment to your PR, I'm thinking about writing some sort of wrapper so we don't force Timber on you, but also still gives users an option to use Timber.  Some Interface with default implementation using android Log, so I can implement it with Timber (above the library, so the library doesn't have a dependencies on Timber).

**Comment by johngray1965** [comment]
I remove Timber from the library, and made a wrapper that uses Android Log by default.  The sample app still use Timber, and provides an example of to config the library to use something other than the default.

**Comment by johngray1965** [comment]
Closing

**Comment by johngray1965** [comment]
1.0.13 has been pushed to maven, but it usually takes about 1/2 hour before it is available.

**Comment by dorukkangal** [comment]
It is working. Thank you for the quick reply!
