### ISSUE TITLE
Calling PdfPage.getPageSize method causes crash when proguard is enabled

### ISSUE THREAD

**Issue by dorukkangal** [johngray1965/PdfiumAndroidKt#9]
I get a JNI error when I call the page.getPageSize method when Proguard is enabled

You can find the error log [here](https://github.com/johngray1965/PdfiumAndroidKt/files/12802361/error.log)

You can use this branch to reproduce the error:
https://github.com/dorukkangal/PdfiumAndroidKt/tree/get-page-size-jni-error

**Comment by johngray1965** [comment]
Hmm, sorry about that.  I'm using it in an app now, I have not pushed a release built out with it just yet (very soon).
Obviously, we'll need some proguard rules.  I'll try to run my app with proguard (R8 really) enabled today.

**Comment by johngray1965** [comment]
1.0.14 fixes the issues.

**Comment by dorukkangal** [comment]
Super! Thank you very much

**Comment by johngray1965** [comment]
You're very welcome, and Thank you so much for reporting.    I really want to make sure bug free and it's very handy when somebody let's me know.
